name/CI

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      os: [ubuntu-latest, windows-latest, macos-latest]
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11, 3.12]
    name: Test
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3